services:
  airline-hub:
    build: ./airlines-hub
    container_name: airlines-hub
    ports:
      - "8081:8081"
    networks:
      - app-network
  exchange:
    build: ./exchange
    container_name: exchange
    ports:
      - "8082:8082"
    networks:
      - app-network

  fidelity:
    build: ./fidelity
    container_name: fidelity
    ports:
      - "8083:8083"
    networks:
      - app-network

  imd-travel:
    build: ./imd-travel
    container_name: imd-travel
    ports:
      - "8080:8080"
    environment:
      - AIRLINES_HUB_URL=http://airlines-hub:8081
      - EXCHANGE_URL=http://exchange:8082
      - FIDELITY_URL=http://fidelity:8083
    depends_on:
      - airline-hub
      - fidelity
      - exchange
    networks:
      - app-network

networks:
  app-network:
    driver: bridge